title: Guilherme DEV Blog
description: "Apenas algumas linhas de código e um pouco do que ando estudando."
author:
  name: Guilherme Ferreira
  email: 'guilherme@uft.edu.br'
  url: guilhermebferreira.github.
  logo:
  gravatar: guilherme@uft.edu.bg
  description: "Python/PHP backend developer."
blog:
  route: ''
metadata:
    description: 'Personal blog, com tématica voltada para programação e desenvolvimento de software.'
taxonomies: [category,tag,month]

summary:
  size: 100
  striptags: true

# Image must be uploaded to your theme /images/ directory.
global_featured_image: featured.jpg

social:
  - text: home
    url: "http://guilhermebferreira.github.io"
  - text: twitter
    url: "http://twitter.com/Guilh_rm_"
  - text: linkedin
    url: "https://www.linkedin.com/in/guilherme-ferreira-dev/"

slider:
  - image: 3.png
    title: Guilherme DEV Blog
    url: "/pt/blog/"
  - image: 1.png
    title: Minha participação no 2ª Hackaton da Faculdade Catolica
    url: "/pt/blog/hackaton"
  - image: 2.png
    title: Crie um blog estático utilizando Pelican
    url: "/pt/blog/pelican"

menu:
  - url: "/resume/about.html"
    text: Sobre mim

# Copyright
copyright: Construido com  <a href="http://www.getgrav.org" rel="dofollow" target="_blank" title="Grav">Grav</a>, tema original por <a title="WebMan WordPress Themes" href="http://www.webmandesign.eu/"><strong>WebMan Design</strong></a>
